version: 2
updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # Only specific requirements are specified in Gemfile, so don't touch it.
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # All versions are specified in package.json, so please update them.
    versioning-strategy: increase
